# Main Configuration
# Core settings and feature toggles

default-channel: "global"
chat-cooldown: 3

debug:
  enabled: false
  verbose-startup: false
  format-processing: false
  cross-server: false
  placeholder-resolution: false

features:
  format-hover: false
  clickable-links: true
  player-formatting: false
  use-group-format: true
  allow-self-messaging: false
  parse-placeholders-in-messages: true
  parse-papi-placeholders-in-messages: false

url-formatting:
  enabled: true
  color: "#3498DB"
  underline: true
  hover-text: "<#AAAAAA>Click to open"

config-files:
  channels: "channels.yml"
  groups: "groups.yml"
  templates: "templates.yml"
  cross-server: "cross-server.yml"
  database: "database.yml"
  discord: "discord.yml"

performance:
  message-queue-size: 1000
  batch-processing: true
  batch-size: 50
  player-cache-size: 500
  channel-cache-size: 100
  cache-cleanup-interval: 300
  async-processing: true
  thread-pool-size: 4

integrations:
  placeholder-api: true
  discord-srv: true
  vault: true
  luckperms: true

security:
  rate-limit:
    enabled: true
    messages-per-minute: 30
    burst-limit: 5
  spam-protection:
    enabled: true
    duplicate-threshold: 3
    similarity-threshold: 0.8
  content-filter:
    enabled: false
    blocked-words: []
    replacement-char: "*"

maintenance:
  auto-save-interval: 300
  cleanup-old-data: true
  data-retention-days: 30
  backup-configs: true

legacy:
  bungeecord-messaging:
    enabled: false

chat-format: "%group_prefix% %player_name%: %message%"

monitoring:
  enabled: true
  statistics-logging: false
  alerts:
    enabled: false
    high-memory-threshold: 0.8
    slow-query-threshold: 1000
  metrics-collection-interval: 60
  statistics-retention-hours: 24
