name: RemmyChat
version: '${project.version}'
main: com.noximity.remmyChat.RemmyChat
api-version: '1.21.8'
depend: []
softdepend: [PlaceholderAPI, LuckPerms, ProtocolLib]
authors: [matcldr]
description: A professional chat plugin with MiniMessage support
website: https://noximity.com #under construction

commands:
  remchat:
    description: Main command for RemmyChat
    usage: /remchat
    aliases: [rc]
    permission: remmychat.use

  msg:
    description: Send a private message to a player
    usage: /msg <player> <message>
    aliases: [tell, pm, whisper, w]
    permission: remmychat.msg

  reply:
    description: Reply to the last player who messaged you
    usage: /reply <message>
    aliases: [r]
    permission: remmychat.msg

  msgtoggle:
    description: Toggle private messages on or off
    usage: /msgtoggle
    aliases: [togglemsg, togglepm]
    permission: remmychat.msgtoggle

  socialspy:
    description: Toggle social spy mode to see private messages
    usage: /socialspy
    aliases: [msgspy, spy]
    permission: remmychat.socialspy

permissions:
  remmychat.use:
    description: Allows using the basic plugin commands
    default: true

  remmychat.msg:
    description: Allows sending private messages
    default: true

  remmychat.msgtoggle:
    description: Allows toggling private messages on/off
    default: true

  remmychat.msgtoggle.bypass:
    description: Allows bypassing other players' message toggle
    default: op

  remmychat.socialspy:
    description: Allows using the social spy feature
    default: op

  remmychat.admin:
    description: Allows using administrative commands
    default: op

  remmychat.channel.local:
    description: Allows using the local channel
    default: true

  remmychat.channel.staff:
    description: Allows using the staff channel
    default: op
