name: RemmyChat Build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Retrieve Project Name & Version
        id: project-info
        run: |
          echo "projectName=$(./gradlew properties -q | grep '^archivesBaseName:' | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "projectVersion=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: build-${{ github.run_number }}-${{ github.run_attempt }}
          release_name: Release ${{ steps.project-info.outputs.projectVersion }} build-${{ github.run_number }}
          body: ${{ join(github.event.commits.*.message, ' || ') }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/${{ steps.project-info.outputs.projectName }}-${{ steps.project-info.outputs.projectVersion }}.jar
          asset_name: ${{ steps.project-info.outputs.projectName }}-${{ steps.project-info.outputs.projectVersion }}.jar
          asset_content_type: application/java-archive
