name: Build and Release RemmyChat

on:
  push:
    tags:
      - 'v*'  # Runs when a version tag is pushed (e.g., v1.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build RemmyChat with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Upload RemmyChat JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: RemmyChat-JAR
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download RemmyChat build artifact
        uses: actions/download-artifact@v4
        with:
          name: RemmyChat-JAR
          path: target/

      - name: Create GitHub Release for RemmyChat
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "RemmyChat ${{ github.ref_name }}"
          body: "New release for RemmyChat! Download the latest version below."
          files: target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
